---
- name: add jessie backports repository
  template:
    src: "jessie_backports.list.j2"
    dest: "/etc/apt/sources.list.d/jessie_backports.list"
    mode: 0644
    owner: root
    group: root
  tags:
    - jessie_backports
    - template
    - copy_configuration_file

- name: update package cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ CACHE_VALID_TIME }}"
  tags:
    - jessie_backports
    - apt
    - update_package

- name: dist-upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: "{{ CACHE_VALID_TIME }}"
  tags:
    - jessie_backports
    - apt
    - dist_upgrade_packages
